#!/bin/sh
set -e
set -u

control_dir="$(dirname $0)"
. $control_dir/config

cmd="$java -jar $control/sbt-launch.jar -Djava.io.tmpdir=\"$tmp_dir\" -Dapp.port=$port"
for file in `ls $control_dir/java-opts-* | sort`; do
    cmd="$cmd `cat $file`"
done
cmd="$cmd $args"

cd $working
exec bash -c "$cmd"