#!/bin/sh
set -e
set -u

control_dir="$(dirname $0)"
. $control_dir/config

export LEIN_JAVA_CMD=$java
export LEIN_JVM_OPTS="-Djava.io.tmpdir=\"$tmp_dir\""
export PORT="$port"

cmd="LEIN_JAVA_CMD= $lib_dir/lein"
for file in `ls $control_dir/lein-opts-* | sort`; do
    cmd="$cmd `cat $file`"
done
cmd="$cmd $args"

cd $working
exec bash -c "$cmd"
